import type { Metadata } from "next";
import { Inter, Charm } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";

const charm = Charm({
  weight: ['400', '700'],
  variable: "--font-charm",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${inter.className} ${charm.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex flex-col min-h-full">
        
        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  );
}
